/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteFuncionario;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.senai.projetointegrador.persistencia.ChalePersistencia;
import Classes.Chale;

/**
 *
 * @author MaryBeds
 */
public class ChalesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChalesView
     */
    public ChalesView() {
        initComponents();
        
        try {

            DefaultTableModel model =  (DefaultTableModel) TabelaChales.getModel();
            model.setNumRows(0);
            ChalePersistencia objetoPesistencia = new ChalePersistencia();
            ArrayList lista = objetoPesistencia.listar();
            for(int pos=0;pos<lista.size();pos++){
                String[] saida= new String[2];//novo
                Chale chale = (Chale)(lista.get(pos));//novo
                saida[0]= "" + chale.getNumero();//novo
                saida[1]= chale.getStatus();//novo
                //Incluir nova linha na Tabela
                model.addRow(saida);//novo
            }
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaChales = new javax.swing.JTable();
        FiltrarPressed = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(158, 189, 83));
        jLabel3.setText("STATUS");

        statusComboBox.setBackground(new java.awt.Color(255, 255, 255));
        statusComboBox.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(153, 153, 153));
        statusComboBox.setMaximumRowCount(3);
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIVRE", "OCUPADO", "RESERVADO" }));
        statusComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(158, 189, 83), 2));

        jScrollPane1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        TabelaChales.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        TabelaChales.setForeground(new java.awt.Color(102, 102, 102));
        TabelaChales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Status"
            }
        ));
        TabelaChales.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TabelaChales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaChalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaChales);

        FiltrarPressed.setBackground(new java.awt.Color(255, 255, 255));
        FiltrarPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Filtrar.png"))); // NOI18N
        FiltrarPressed.setBorderPainted(false);
        FiltrarPressed.setContentAreaFilled(false);
        FiltrarPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarPressedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FiltrarPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltrarPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FiltrarPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarPressedActionPerformed
        // TODO add your handling code here:
        try {

            String status = (String)statusComboBox.getSelectedItem();
            System.out.print(status);
            DefaultTableModel model =  (DefaultTableModel) TabelaChales.getModel();
            model.setNumRows(0);
            ChalePersistencia objetoPesistencia = new ChalePersistencia();
            ArrayList lista = objetoPesistencia.listarStatus(status);
            for(int pos=0;pos<lista.size();pos++){
                String[] saida= new String[2];//novo
                Chale chale = (Chale)(lista.get(pos));//novo
                saida[0]= "" + chale.getNumero();//novo
                saida[1]= chale.getStatus();//novo
                //Incluir nova linha na Tabela
                model.addRow(saida);//novo
            }
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_FiltrarPressedActionPerformed

    private void TabelaChalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaChalesMouseClicked
        // TODO add your handling code here:
        int codSelecionado = this.TabelaChales.getSelectedRow();
        String codpro = this.TabelaChales.getValueAt(codSelecionado, 0).toString();

        RegistrarReservaView cod = new RegistrarReservaView(Integer.parseInt(codpro));
        System.out.println("COD CHALE ENVIADO: "+cod.getNumeroRecebidoChale());

        cod.setLocation(385, 45);
        cod.setVisible(true);
        
    }//GEN-LAST:event_TabelaChalesMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FiltrarPressed;
    private javax.swing.JTable TabelaChales;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> statusComboBox;
    // End of variables declaration//GEN-END:variables
}
