/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteFuncionario;

import com.senai.projetointegrador.dependente.DependenteViewCtrl;

/**
 *
 * @author siqueira
 */
public class DependenteView extends javax.swing.JFrame {

	/**
	 * Creates new form DependenteView
	 */
	public DependenteView() {
		this.initComponents();
		this.inicializar();
	}

	private void inicializar() {
		DependenteViewCtrl dependenteViewCtrl = DependenteViewCtrl.getInstancia();
		dependenteViewCtrl.setDependenteView(this);
		dependenteViewCtrl.inicializar();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tfNome = new javax.swing.JTextField();
		tfCpf = new javax.swing.JTextField();
		tfData = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		btnSalvar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Nome");

		jLabel2.setText("CPF");

		jLabel3.setText("Data de nascimento");

		jLabel4.setText("Parentesco");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filho", "Esposa" }));

		btnSalvar.setBackground(new java.awt.Color(0, 153, 0));
		btnSalvar.setText("Salvar");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addGap(21, 21, 21).addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2).addComponent(jLabel1).addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(btnSalvar).addGroup(jPanel1Layout
																.createSequentialGroup().addGroup(
																		jPanel1Layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabel3)
																				.addComponent(jLabel4))
																.addGap(32, 32, 32)
																.addGroup(jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(tfCpf).addComponent(tfNome)
																		.addComponent(tfData).addComponent(jComboBox1,
																				0, 297, Short.MAX_VALUE)))))
										.addContainerGap(15, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(33, 33, 33)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(39, 39, 39)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(52, 52, 52)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										30, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(21, 21, 21).addComponent(btnSalvar).addContainerGap()));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DependenteView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DependenteView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DependenteView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DependenteView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DependenteView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSalvar;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField tfCpf;
	private javax.swing.JTextField tfData;
	private javax.swing.JTextField tfNome;
	// End of variables declaration//GEN-END:variables

	/**
	 * @return the jComboBox1
	 */
	public javax.swing.JComboBox<String> getjComboBox1() {
		return jComboBox1;
	}

	/**
	 * @param jComboBox1
	 *            the jComboBox1 to set
	 */
	public void setjComboBox1(javax.swing.JComboBox<String> jComboBox1) {
		this.jComboBox1 = jComboBox1;
	}

	/**
	 * @return the tfCpf
	 */
	public javax.swing.JTextField getTfCpf() {
		return tfCpf;
	}

	/**
	 * @param tfCpf
	 *            the tfCpf to set
	 */
	public void setTfCpf(javax.swing.JTextField tfCpf) {
		this.tfCpf = tfCpf;
	}

	/**
	 * @return the tfData
	 */
	public javax.swing.JTextField getTfData() {
		return tfData;
	}

	/**
	 * @param tfData
	 *            the tfData to set
	 */
	public void setTfData(javax.swing.JTextField tfData) {
		this.tfData = tfData;
	}

	/**
	 * @return the tfNome
	 */
	public javax.swing.JTextField getTfNome() {
		return tfNome;
	}

	/**
	 * @param tfNome
	 *            the tfNome to set
	 */
	public void setTfNome(javax.swing.JTextField tfNome) {
		this.tfNome = tfNome;
	}

	/**
	 * @return the btnSalvar
	 */
	public javax.swing.JButton getBtnSalvar() {
		return btnSalvar;
	}

	/**
	 * @param btnSalvar
	 *            the btnSalvar to set
	 */
	public void setBtnSalvar(javax.swing.JButton btnSalvar) {
		this.btnSalvar = btnSalvar;
	}

}
