/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteFuncionario;

import Classes.Chale;
import Classes.Reserva;
import Classes.Socio;
import com.senai.projetointegrador.persistencia.ChalePersistencia;
import com.senai.projetointegrador.persistencia.ReservaPersistencia;
import com.senai.projetointegrador.persistencia.SocioPersistencia;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MaryBeds
 */
public class RegistrarReservaView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarReservaView
     */
    
    String socioSelected;
    private int numeroRecebidoChale;

    public int getNumeroRecebidoChale() {
        return numeroRecebidoChale;
    }

    public void setNumeroRecebidoChale(int numeroRecebidoChale) {
        this.numeroRecebidoChale = numeroRecebidoChale;
    }

    public RegistrarReservaView(int numero) {
        
        this.numeroRecebidoChale = numero;
        
        initComponents();
        
        String numeroString = Integer.toString(numeroRecebidoChale);
        System.out.println("COD CHALE: "+numeroString);
        numChaleLbl.setText(numeroString);

        try {
            
            ChalePersistencia objetoPesistencia = new ChalePersistencia();
            ArrayList lista = objetoPesistencia.exibirChale(numeroRecebidoChale);
            for(int pos=0;pos<lista.size();pos++){
                String[] saida= new String[2];
                Chale chale = (Chale)(lista.get(pos));
                saida[0] = chale.getDescricao();
                saida[1] = chale.getStatus();
                
                System.out.println("DESCRICAO CHALE: "+saida[0]);
                System.out.println("STATUS CHALE: "+saida[1]);

                
                descricao.setText(saida[0]);
                statusLbl.setText(saida[1]);
            }
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
        
        try {
            DefaultComboBoxModel comboBox = (DefaultComboBoxModel) socioComboBox.getModel();
            SocioPersistencia objetoPesistencia = new SocioPersistencia();
            ArrayList lista = objetoPesistencia.listar();
            for(int pos=0;pos<lista.size();pos++){
                String[] saida= new String[1];//novo
                Socio socio = (Socio)(lista.get(pos));//novo
                saida[0] = socio.getNome();//novo
                comboBox.addElement(saida[0]);
            }
            
            socioSelected = socioComboBox.getItemAt(0);
            System.out.println(socioSelected);
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }

    }
    

    public RegistrarReservaView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VoltarPressed = new javax.swing.JButton();
        voltarLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numChaleLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        socioComboBox = new javax.swing.JComboBox<>();
        ReservarPressed = new javax.swing.JButton();
        ExcluirPressed = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dataTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        VoltarPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        VoltarPressed.setBorderPainted(false);
        VoltarPressed.setContentAreaFilled(false);
        VoltarPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarPressedActionPerformed(evt);
            }
        });

        voltarLbl.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        voltarLbl.setForeground(new java.awt.Color(158, 189, 83));
        voltarLbl.setText("VOLTAR");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("STATUS:");

        statusLbl.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        statusLbl.setForeground(new java.awt.Color(153, 153, 153));
        statusLbl.setText("LIVRE");

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("SÓCIO:");

        numChaleLbl.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        numChaleLbl.setForeground(new java.awt.Color(153, 153, 153));
        numChaleLbl.setText("0");

        jLabel4.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("DESCRIÇÃO:");

        descricao.setColumns(20);
        descricao.setRows(5);
        descricao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(descricao);

        jLabel5.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("NÚMERO:");

        socioComboBox.setBackground(new java.awt.Color(255, 255, 255));
        socioComboBox.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        socioComboBox.setForeground(new java.awt.Color(153, 153, 153));
        socioComboBox.setMaximumRowCount(100);

        ReservarPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Reservar.png"))); // NOI18N
        ReservarPressed.setBorderPainted(false);
        ReservarPressed.setContentAreaFilled(false);
        ReservarPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarPressedActionPerformed(evt);
            }
        });

        ExcluirPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        ExcluirPressed.setBorderPainted(false);
        ExcluirPressed.setContentAreaFilled(false);
        ExcluirPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirPressedActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("DATA DA RESERVA:");

        dataTxtField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        dataTxtField.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(VoltarPressed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(voltarLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(dataTxtField)
                                .addComponent(socioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numChaleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(ReservarPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(ExcluirPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarPressed)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltarLbl)
                            .addComponent(jLabel2)
                            .addComponent(statusLbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numChaleLbl)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReservarPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarPressedActionPerformed
        // TODO add your handling code here:
        System.out.print("VOLTAR");
       FuncionarioInterface chaleFrame = new FuncionarioInterface(0);
       chaleFrame.setVisible(true);

              
    }//GEN-LAST:event_VoltarPressedActionPerformed

    private void ReservarPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarPressedActionPerformed
        // TODO add your handling code here:
        
        try {
           
            String socio = (String)socioComboBox.getSelectedItem();
            if (socio.length() == 0) {
                socio = socioSelected;
            }
            
            String dataReserva = dataTxtField.getText();
            
            int numChale = Integer.parseInt(numChaleLbl.getText());
            System.out.println(numChale);
            Reserva objetoChale = new Reserva(dataReserva,  numChale, socio);
            
            ReservaPersistencia objetoPesistenciaChale = new ReservaPersistencia();
            ArrayList lista = objetoPesistenciaChale.verificarDataDisponivel(dataReserva, numChale);
          
            if (lista.isEmpty()) {
                objetoPesistenciaChale.incluirReserva(objetoChale);
                Chale objeto = new Chale("Teste de edição no Java", "RESERVADO", numChale);
            
                ChalePersistencia objetoPesistencia = new ChalePersistencia() {};
                objetoPesistencia.editar(objeto);

                JOptionPane.showMessageDialog(null, "CHALÉ RESERVADO COM SUCESSO");
                
            } else {
                JOptionPane.showMessageDialog(null, "CHALÉ INDISPONÍVEL NESTA DATA");
            }
            
            
            
            
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(RegistrarReservaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReservarPressedActionPerformed

    private void ExcluirPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirPressedActionPerformed
        // TODO add your handling code here:
        try {
           
            ChalePersistencia objetoPesistencia = new ChalePersistencia();
            objetoPesistencia.excluir(numeroRecebidoChale);
            ChalesView chalesFrame = new ChalesView();
            chalesFrame.setVisible(false);
            
            JOptionPane.showMessageDialog(null, "CHALÉ EXCLUÍDO COM SUCESSO");

        } catch (NumberFormatException | SQLException erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(ReservarChale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExcluirPressedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarReservaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirPressed;
    private javax.swing.JButton ReservarPressed;
    private javax.swing.JButton VoltarPressed;
    private javax.swing.JTextField dataTxtField;
    private javax.swing.JTextArea descricao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numChaleLbl;
    private javax.swing.JComboBox<String> socioComboBox;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel voltarLbl;
    // End of variables declaration//GEN-END:variables
}
